Field effect system
BluRosie/hg-engine pull request #163
Opened 2023-12-10 14:32 UTC by Aeliko

- Implement Grassy Terrain, Electric Terrain, Misty Terrain, Psychic Terrain
- Implement way to add custom effects before move is queued (`345.s`)
- Implement way to add custom effects at the first turn (`346.s`)
- Implement way to add custom effects at the end of the turn (`347.s`)
- Implement "framework" to add "field effects"
- Implement toggle to turn off "field effects" (default off)

2023-12-11 20:45 UTC, BluRosie requested changes
how do you manage damage calc modifications for each terrain?  also jotted down a bunch that isn't mainline behavior so it isn't suitable for hg-engine outside of a personal hack.  i can deal with the things i notice if you don't feel like doing it, i guess just let me know haha

2023-12-11 20:45 UTC, BluRosie commented on armips/move/battle_eff_seq/155.s
> +    ifcurrentfieldistype TERRAIN_CAVE, _0064
please remove custom effects (if you want i can do it)

2023-12-11 20:45 UTC, BluRosie commented on armips/move/battle_eff_seq/263.s
> +    ifcurrentfieldistype TERRAIN_CAVE, _0064
custom effects

2023-12-11 20:45 UTC, BluRosie commented on armips/move/battle_sub_seq/217.s
> +    checkitemeffect 0x1, BATTLER_ATTACKER, 0x63, SkipRemoveItem
more custom effect stuff

2023-12-11 20:45 UTC, BluRosie commented on armips/move/battle_sub_seq/316.s
> +    endscript
does coil raise stats 2x in grassy terrain?  i don't actually know lol

2023-12-11 20:45 UTC, BluRosie commented on armips/move/battle_sub_seq/331.s
> +    ifcurrentfieldistype TERRAIN_GRASS, SunIsUp // gain double of the normal stat-changing effects in grass terrain
same here as coil

2023-12-11 20:45 UTC, BluRosie commented on armips/move/battle_sub_seq/345.s
> +            endscript
are these all vanilla interactions?

2023-12-11 20:45 UTC, BluRosie commented on armips/move/battle_sub_seq/345.s
> +            endscript
same with all the cool interactions
while they are good ideas, i don't mean to merge them into an engine that is aiming to implement parity with later generations

2023-12-11 20:45 UTC, BluRosie commented on armips/move/battle_sub_seq/346.s
> +    endscript
just jotting more things

2023-12-11 20:45 UTC, BluRosie commented on data/text/197.txt
> +The quake collapsed the ceiling!
All this stuff too

2023-12-11 20:45 UTC, BluRosie commented on include/battle.h
> +    TerrainOverlay terrainOverlay;
could potentially just put this in the main BattleStruct

2023-12-11 20:45 UTC, BluRosie commented on include/debug.h
> +// #define DEBUG_TERRAIN
need your own debug define for terrain (if you use this at all)

2023-12-11 20:45 UTC, BluRosie commented on src/battle/ability.c
> +}
potentially just do like.  IsClientGrounded or something, it's a general-use func that can be used wherever

2023-12-31 02:10 UTC, BluRosie commented
hoping to review this tonight and get it merged!!

2024-01-03 14:49 UTC, NathanWichers approved these changes
looks good to me!  anything else you want to overhaul?

2024-01-04 02:14 UTC, BluRosie approved these changes

2024-01-04 20:42 UTC, merged