Miscellaneous changes
BluRosie/hg-engine pull request #264
Opened 2024-06-06 13:08 UTC by Aeliko

- [x] Lightningrod -> Lightning Rod
- [x] Weather Ball no longer changes move split in certain conditions
- [x] Newer Moves that change Type and Moves that change Type due to Abilities can be redirected
- [ ] Assault Vest
- [ ] Gigaton Hammer

2024-06-18 13:31 UTC, BluRosie requested changes

2024-06-18 13:32 UTC, BluRosie commented on data/battle_scripts/effects/effect_script_0282_ALWAYS_CRITICAL.s
> +    UpdateVar OPCODE_SET, BSCRIPT_VAR_CRIT_MULTIPLIER, 0x2
unless if you deleted it there and i am just blind

2024-06-19 05:00 UTC, Aeliko commented on src/battle/other_battle_calculators.c
> +    return GetAdjustedMoveTypeBasics(ctx, moveNo, GetBattlerAbility(ctx, battlerId), type);
(Posting here also for better "documentation")
`GetDynamicMoveType`: For moves that change type, probably used to see if Water type Judgement needs to be redirected, etc. However with the introduction of Liquid Voice, -ate abilities, etc., the vanilla check is too naive
`GetAdjustedMoveTypeBasics`: just for Normalize, we added the other abilities here

2024-06-22 17:55 UTC, BluRosie approved these changes

2024-06-25 13:29 UTC, merged