Handle contact modern mecanics
BluRosie/hg-engine pull request #311
Opened 2024-09-03 12:27 UTC by Mixone-FinallyHere

Handles contact with modern mecanics and leaves easy framework to add or remove item effects and abilities that can prevent contact

It includes also the stuff for PR #310 i edited that on main instead of a branch so its all together (sorry)

2024-09-03 19:52 UTC, BluRosie commented
so...  we know that this covers the existing contact things in hg-engine, do we know about everything beyond this as well?  or are we thinking of tackle it as needed?

2024-09-04 11:32 UTC, Mixone-FinallyHere commented
> so... we know that this covers the existing contact things in hg-engine, do we know about everything beyond this as well? or are we thinking of tackle it as needed?

Im not SUPER familiar with like the most modern mecanics but between mojo and aero they mentioned all cases for contact that exist (PGloves + PPads and Long Reach)

The idea is that since the door is left open to easily add others, if in the future we see more its easy to simply append to this function I would say

TL;DR: As far as I know this tackles all possible use cases ASSUMING that neutralizing gas will be implemented at CheckAbility level

2024-10-16 13:39 UTC, BluRosie requested changes

2024-10-16 13:39 UTC, BluRosie commented on src/battle/other_battle_calculators.c
> +    }
where is this linked into vanilla?  currently seems like it would recursively call itself and would likely stack overflow

2024-10-16 13:39 UTC, BluRosie commented on src/battle/other_battle_calculators.c
> +    }
should probably just be `sp->moveTbl[sp->current_move_index].flag & FLAG_CONTACT`

2024-10-21 13:28 UTC, BluRosie approved these changes

2024-10-21 13:28 UTC, merged