Battle engine revamp (turn sequence)
BluRosie/hg-engine pull request #337
Opened 2024-10-20 12:17 UTC by Aeliko

WIP

Remind me to either draw a diagram here or create a wiki page explain what and why we need this.

2024-11-19 00:01 UTC, Aeliko commented
> do you need anything from me to get this working?

Not yet, just need a code review when I finish soon™️

2025-01-02 15:23 UTC, BluRosie commented
what do you yet need to do for this?

2025-01-02 15:25 UTC, Aeliko commented
Check move failures 4
Quick Claw and Custap berry subscript

2025-01-04 09:24 UTC, Aeliko commented
Uhh probably need to revert and force push again

2025-01-05 18:51 UTC, BluRosie requested changes

2025-01-05 18:51 UTC, BluRosie commented on src/battle/other_battle_calculators.c
> +void LONG_CALL CalcPriorityAndQuickClawCustapBerry(void *bsys, struct BattleStruct *ctx) {
i'm sorry--where is this called now?

2025-01-05 18:51 UTC, BluRosie commented on src/battle/other_battle_calculators.c
> +}
good question as to whether or not creating a local copy here is a good idea.  i guess it's all on the stack, but then it requires reading every 32-bit word in a `BattlePokemon` to copy it to the stack
negligible performance thing though so whatever

2025-01-05 18:51 UTC, BluRosie commented on src/field/enemy_party.c
> +    u32 micacleSeedItemNo = ITEM_MIRACLE_SEED;
micacle

2025-01-05 18:51 UTC, BluRosie commented on src/pokemon.c
> +#endif
gender differences should be default on?  same for basculegion/pyroar?

2025-01-05 23:28 UTC, Aeliko commented on data/battle_scripts/subscripts/subscript_0039_HURT_SELF_IN_CONFUSION.s
> +// TODO: Modernise confusion damage
No

2025-01-05 23:31 UTC, Aeliko commented on data/battle_scripts/subscripts/subscript_0264_TYPE_RESIST_BERRY_DAMAGE.s
It is like this in the decomp as well. Copied from the original subscript

2025-01-06 05:01 UTC, Aeliko commented on src/pokemon.c
> +#endif
Different BSTs and abilities, that's why they are excluded

2025-01-06 05:09 UTC, Aeliko commented on data/battle_scripts/subscripts/subscript_0278_CHECK_QUICK_CLAW.s
> +// TODO Loop over battlers here
Handled, forgot to remove TODO

2025-01-06 05:11 UTC, Aeliko commented on src/battle/other_battle_calculators.c
> +void LONG_CALL CalcPriorityAndQuickClawCustapBerry(void *bsys, struct BattleStruct *ctx) {
`ServerBeforeAct`

2025-01-06 12:31 UTC, Aeliko commented on data/battle_scripts/effects/effect_script_0332_ACC_UP_3.s
Implemented for completeness

2025-01-06 12:37 UTC, Aeliko commented on data/battle_scripts/subscripts/subscript_0252_SNOW_WARNING.s
> +    PlayBattleAnimation BATTLER_CATEGORY_PLAYER, BATTLE_ANIMATION_WEATHER_SNOW
Not sure of the syntax of using `.if` in these files

2025-01-07 15:05 UTC, Aeliko commented on data/battle_scripts/subscripts/subscript_0039_HURT_SELF_IN_CONFUSION.s
> +// TODO: Modernise confusion damage
[https://bulbapedia.bulbagarden.net/wiki/Confusion_(status_condition)#Effect](https://bulbapedia.bulbagarden.net/wiki/Confusion_(status_condition)#Effect)

2025-01-07 21:32 UTC, BluRosie commented on include/battle.h
> +
actually resolved this with cfd6cbf28e3bcb47b8e71ad55326db3cd3d31c28

2025-01-07 21:44 UTC, BluRosie commented on src/battle/other_battle_calculators.c
> +        if (TypeEffectivenessTable[i][0] == 0xfe)  // handle foresight
you introduced constants for foresight type and did not use them
```c
// Special type table IDs
#define TYPE_FORESIGHT 0xFE
#define TYPE_ENDTABLE  0xFF
```

2025-01-07 21:44 UTC, BluRosie commented on src/field/enemy_party.c
> +
i'm just going to fix this properly by setting the held item factoring in the form

2025-01-07 22:17 UTC, BluRosie commented on src/field/enemy_party.c
> +
yea it already works lol
![image](https://github.com/user-attachments/assets/9091ee0a-3026-43e6-9d42-d8dbdd1e0d8c)

2025-01-07 22:25 UTC, BluRosie approved these changes

2025-01-08 22:41 UTC, BluRosie commented on src/individual/BattleController_BeforeMove.c
> +    }
check for mold breaker variations here?

2025-01-08 22:41 UTC, BluRosie commented on src/individual/BattleController_BeforeMove.c
> +        && CLIENT_DOES_NOT_HAVE_MOLD_BREAKER_VARIATIONS(ctx, attacker)) {
this is just something like
```c
if (MoldBreakerAbilityCheck(ctx, attacker, defender, ABILITY_DAMP) == TRUE)
```
this lets us account for i.e. gastro acid much easier as well in one central place that is used wherever is necessary even in vanilla unmodified contexts
https://github.com/BluRosie/hg-engine/blob/4e312bbc85749e6e3743993c4fefe4784a651efb/src/battle/ability.c#L501-L526

2025-01-08 22:41 UTC, BluRosie commented on src/individual/BattleController_BeforeMove.c
> +    && CLIENT_DOES_NOT_HAVE_MOLD_BREAKER_VARIATIONS(ctx, attacker)) {
`MoldBreakerAbilityCheck`

2025-01-09 00:08 UTC, Aeliko commented on src/individual/BattleController_BeforeMove.c
> +    }
Not sure, this is vanilla code. I think it implies if the attacker's ability is Normalize or Mold Breaker then redirection abilities won't trigger.

2025-01-11 12:05 UTC, blackisme1 commented on src/individual/BattleController_BeforeMove.c
> +    || (GetBattlerAbility(ctx, ctx->defence_client) == ABILITY_INSOMNIA || GetBattlerAbility(ctx, ctx->defence_client) == ABILITY_TRUANT)
Worry Seed not affecting Insomnia/Truant targets doesnt have a check for if the move is Worry Seed

2025-01-11 12:11 UTC, Aeliko commented on src/individual/BattleController_BeforeMove.c
> +    || (GetBattlerAbility(ctx, ctx->defence_client) == ABILITY_INSOMNIA || GetBattlerAbility(ctx, ctx->defence_client) == ABILITY_TRUANT)
You're right

2025-01-11 17:11 UTC, blackisme1 commented on src/individual/BattleController_BeforeMove.c
> +    if (((defenderSpecies == SPECIES_GENGAR && defenderForm == 1) || defenderSpecies == SPECIES_DIGLETT || defenderSpecies == SPECIES_DUGTRIO || defenderSpecies == SPECIES_SANDYGAST || defenderSpecie
Telekinesis failing on forcefully grounded mons does not check if the move is Telekinesis

2025-01-12 19:58 UTC, BluRosie commented
per discord conversation...

two more todo before merge:
- [ ] attack message in double battle
- [ ] switch out -> pursuit -> primal reversion -> no attack message

2025-01-23 05:44 UTC, BluRosie commented
![pursuit-primal-message](https://github.com/user-attachments/assets/e3bc15a9-57be-4740-b490-26e2b3e91706)
pursuit -> primal -> desolate land -> attacker message appears to work

2025-01-31 08:40 UTC, blackisme1 commented on data/battle_scripts/subscripts/subscript_0407_ATTACK_MISSED.s
> +.include "asm/include/battle_commands.inc"
This new "attack missed" subscript does not handle HJK's crash damage

2025-01-31 18:46 UTC, BluRosie commented on data/battle_scripts/subscripts/subscript_0407_ATTACK_MISSED.s
> +.include "asm/include/battle_commands.inc"
will have to check if HJK is just broken now or what

2025-02-01 17:37 UTC, blackisme1 commented on src/individual/BattleController_BeforeMove.c
> +    if ((MoldBreakerAbilityCheck(ctx, ctx->attack_client, defender, ABILITY_LEVITATE) == TRUE) && (ctx->move_type == TYPE_GROUND)
Levitate and its friends can only block ground type moves that deal damage (and also not thousand arrows)

2025-02-03 02:32 UTC, BluRosie commented on data/battle_scripts/subscripts/subscript_0407_ATTACK_MISSED.s
> +.include "asm/include/battle_commands.inc"
high jump kick does indeed appear to be broken

2025-02-03 03:04 UTC, BluRosie commented on data/battle_scripts/subscripts/subscript_0407_ATTACK_MISSED.s
> +.include "asm/include/battle_commands.inc"
high jump kick appears to be able to crash because of...
- [ ] missing
- [ ] trying to use it on ineffective type matchup (ghost)
- [ ] protect

2025-02-09 17:54 UTC, merged